[general]
mod_key = "Super"
xwayland = true
focus_on_activate = false
honor_restored_maximize = false
autostart = [
	"noctalia",
	"steam -silent",
]

[input.keyboard]
layout = "pl"

[input.touchpad]
natural_scroll = false

[input.cursor]
theme = "Bibata-Modern-Classic"
size = 24

[input.focus]
follows_mouse = true

[output."HDMI-A-2"]
mode = "3840x2160@60"
position = [0, 0]
scale = 1.5
vrr = "disabled"

[output."DP-4"]
mode = "2560x1440@240"
position = [2560, 0]
scale = 1.0
vrr = "disabled"

[output."eDP-1"]
scale = 1.5

[layout]
mode = "scrolling"
gap = 10

[appearance]
prefer_no_csd = true
border_width = 2
corner_radius = 5

[appearance.blur]
enabled = true
passes = 1
radius = 3
saturation = 1.17

[appearance.shadow]
enabled = true
softness = 4

[animation]
enabled = true

[keybinds]
"Mod+Q" = "spawn:alacritty -e tmux a"
"Mod+Shift+Q" = "spawn:alacritty -e tmux"
"Mod+W" = "spawn:zen"
"Mod+Shift+W" = "spawn:zen --private-window"
"Mod+C" = "window-close"
"Mod+F" = "window-toggle-fullscreen"
"Mod+E" = "spawn:nautilus"
"Mod+B" = "window-toggle-floating"
"Mod+Return" = "spawn:noctalia msg panel-toggle launcher"
"Mod+H" = "window-focus-or-output-left"
"Mod+L" = "window-focus-or-output-right"
"Mod+K" = "window-focus-or-output-up"
"Mod+J" = "window-focus-or-output-down"
"Mod+Shift+H" = "window-move-or-output-left"
"Mod+Shift+L" = "window-move-or-output-right"
"Mod+Shift+K" = "window-move-up"
"Mod+Shift+J" = "window-move-down"
"Mod+Shift+A" = "window-move-to-output-left"
"Mod+Shift+F" = "window-move-to-output-right"
"Mod+U" = "window-modify-primary-extent:+0.1"
"Mod+P" = "window-modify-primary-extent:-0.1"
"Mod+I" = "window-modify-secondary-extent:+0.1"
"Mod+O" = "window-modify-secondary-extent:-0.1"
"Mod+Escape" = "spawn:noctalia msg session lock"
"Mod+S" = "spawn:noctalia msg screenshot-region"
"Mod+N" = "spawn:noctalia msg panel-open control-center notifications"
"Mod+Tab" = "spawn:noctalia msg panel-open session"
"Mod+V" = "spawn:noctalia msg panel-toggle clipboard"
"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"
"Mod+0" = "workspace-switch:10"
"Mod+Shift+1" = "window-move-to-workspace:1"
"Mod+Shift+2" = "window-move-to-workspace:2"
"Mod+Shift+3" = "window-move-to-workspace:3"
"Mod+Shift+4" = "window-move-to-workspace:4"
"Mod+Shift+5" = "window-move-to-workspace:5"
"Mod+Shift+6" = "window-move-to-workspace:6"
"Mod+Shift+7" = "window-move-to-workspace:7"
"Mod+Shift+8" = "window-move-to-workspace:8"
"Mod+Shift+9" = "window-move-to-workspace:9"
"Mod+Shift+0" = "window-move-to-workspace:10"
"Mod+WheelUp" = { action = "workspace-previous", cooldown_ms = 150 }
"Mod+WheelDown" = { action = "workspace-next", cooldown_ms = 150 }
"XF86AudioRaiseVolume" = { action = "spawn:wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+", allow_when_locked = true }
"XF86AudioLowerVolume" = { action = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-", allow_when_locked = true }
"XF86AudioMute" = { action = "spawn:wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle", allow_when_locked = true }
"XF86AudioMicMute" = { action = "spawn:wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle", allow_when_locked = true }
"XF86MonBrightnessUp" = { action = "spawn:brightnessctl -e4 -n2 set 5%+", allow_when_locked = true }
"XF86MonBrightnessDown" = { action = "spawn:brightnessctl -e4 -n2 set 5%-", allow_when_locked = true }
"XF86AudioNext" = "spawn:playerctl next"
"XF86AudioPause" = "spawn:playerctl play-pause"
"XF86AudioPlay" = "spawn:playerctl play-pause"
"XF86AudioPrev" = "spawn:playerctl previous"

[[window_rule]]
match.app_id = "^Alacritty$"
default_scrolling_extent = 1.0

[[window_rule]] # steam notification toasts
match.title = "^notificationtoasts_.+_desktop"
default_position = { x = 0, y = 0, anchor = "bottom_right" }
default_focused = false
default_pinned = true

[[layer_rule]]
match.namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$"
blur = true
blur_popups = true
blur_ignore_alpha = 0.5

[include.optional]
files = ["noctalia.toml"]
